### ISSUE TITLE
Content type is incorrect, should use multipart/form-data

### ISSUE THREAD

**Issue by jimmywarting** [ajaska/formdata-polyfill#1]
there is a more complete polyfill here that are more closer to the spec
https://github.com/jimmywarting/FormData

it also patches xhr and fetch.
also fixes the file constructor in browser who throw when constructing a new file

it also able to accept a form element in it's constructor

It also sends it as multipart/form-data of which you are able to append files to the formdata. your urlEncoded dose not, Quite important to know this in your readme...

Here is a idea, depricate this repo and redirect them to my formdata polyfill

**Comment by ajaska** [comment]
meh
